### ISSUE TITLE
Plans to Update GUI Config Screen for 1.17.1

### ISSUE THREAD

**Issue by TrevorSlobodnick** [Leo3418/HBWHelper#4]
I followed your tutorial on how to build a gui for my mod configuration in Minecraft (1.16.5), and I got it working pretty quickly. But now that Im trying to update my mod to 1.17.1, It seems like a lot of the classes you used have changed (removed, moved to a new location, etc). Needless to say, Im totally lost and have no idea how to move forward. Which leads me to my question, Do you have any plans on making a follow up guide for 1.17.1?

**Comment by Leo3418** [comment]
Hi TrevorSlobodnick!  Please be informed that the issue tracker for HBWHelper is intended to be used only for bugs in HBWHelper itself.  Because I have many other things that keep me busy, I cannot provide mod development assistance here.  Regarding your inquiry, this mod will not be ported to 1.17.x yet until Minecraft Forge releases a *recommended build* for it, and I might update the guide you mentioned if time permits.
